name: Build & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: '1.1.2'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build project
        # Using **/*.csproj automatically finds your project file in any subfolder
        run: |
          dotnet restore **/*.csproj
          dotnet publish **/*.csproj -c Release -r win-x64 --self-contained true -o build_output

      - name: Zip output
        # Zips everything inside the build_output folder
        run: Compress-Archive -Path .\build_output\* -DestinationPath MasterRelayVPN.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MasterRelayVPN-Artifact
          path: MasterRelayVPN.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: MasterRelayVPN.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
